services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.micropython
    volumes:
      - './:/home/micropython/app'
    command: micropython test_runner.py

  lint:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - './:/app'
    command: ruff --config ./ruff.toml check --no-cache

  format:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - './:/app'
    command: ruff --config ./ruff.toml format --no-cache
