services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.micropython
    volumes:
      - './:/home/micropython/app'
    user: "100:101"
    command: micropython test_runner.py

  lint:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - './:/app'
    user: "100:101"
    command: ruff --config ./ruff.toml check

  format:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - './:/app'
    user: "100:101"
    command: ruff --config ./ruff.toml format
