services:
  web-ui-install:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - './web-ui:/app'
    command: pnpm install

  core-test:
    build:
      context: .
      dockerfile: Dockerfile.micropython
    volumes:
      - './:/app'
    command: micropython test_runner.py

  core-lint:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - './:/app'
    command: ruff --config ./ruff.toml check --no-cache

  web-ui-lint:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - './web-ui:/app'
    command: pnpm run lint

  core-format:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - './:/app'
    command: ruff --config ./ruff.toml format --no-cache

  core-build:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - './:/app'
    command: make build-core

  web-ui-build:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - './web-ui:/app'
    command: pnpm build