name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create self signed cert
        run: create-self-signed-certificate

      - name: Clone MicroPython
        run: |
          git clone -b v1.26.0 https://github.com/micropython/micropython.git
          git -C micropython submodule update --init --recursive

      - name: Compile mpy-cross
        run: |
          cd micropython/mpy-cross
          make

      - name: Build Firmware
        run: |
          cd micropython/ports/esp32
          make BOARD=ESP32_GENERIC_C6 FROZEN_MANIFEST=../../../manifest.py

      - name: Archive and upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: tank-buddy
          path: micropython/ports/esp32/build-ESP32_GENERIC_C6/firmware.bin
          retention-days: 7