name: CI

on:
  pull_request

jobs:
  continous-integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Build docker images
      run: make docker-build-images

    - name: Run ruff (linting)
      run: make docker-lint
      continue-on-error: false

    - name: Run tests
      run: make docker-test
      continue-on-error: false